### ISSUE TITLE
`sct_deepseg_lesion` and `sct_deepseg_sc` with `-r 0` do not keep centerline

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#3956]
### Description

For debugging purposes, I want to check the centerline detected within the `sct_deepseg_lesion`. Since the centreline is not a standard output of this function, we used the flag `-r 0` to not delete temporary files. However, even with this flag, the centreline is still deleted.

### Steps to Reproduce

0. Download a test subject

```
git clone git@data.neuro.polymtl.ca:datasets/canproco
cd canproco
git annex get sub-mon001
cd sub-mon001/ses-M0/anat 
```

1. Run `sct_deepseg_lesion` function on `T2w` sagittal image.

```
sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -v 1 -r 0
```

Note: Although, `-r 0` is used to keep temporary files, the temporary folder with the centreline is deleted, see `rm -rf` line in the output.

<details><summary>output</summary>

```
$ sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -v 1 -r 0                                         

--
Spinal Cord Toolbox (git-master-c57b43f715cb85dad87a33623c7caf0ed47543ca)

sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -v 1 -r 0
--


Method:
	Centerline algorithm: svm
	Assumes brain section included in the image: False

Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122133419.051444-xt9ohgrv)
Reorient the image to RPI, if necessary...

Finding the spinal cord centerline...
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122133425.506625-2jy950w_)
Remove temporary files...
rm -rf /var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122133425.506625-2jy950w_

Cropping the image around the spinal cord...
Normalizing the intensity...
load data...

Segmenting the MS lesions using deep learning on 3D patches...
load data...

Reassembling the image...
Resampling the segmentation to the original image resolution...
load data...

Binarizing the segmentation to avoid interpolation effects...

Reorienting the segmentation to the original image orientation...

Done! To view results, run one of the following commands (depending on your preferred viewer):
fsleyes sub-mon001_ses-M0_T2w.nii.gz -cm greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_lesionseg.nii.gz -cm red -a 70.0 &

fslview_deprecated sub-mon001_ses-M0_T2w.nii.gz -l Greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_lesionseg.nii.gz -l Red -t 0.7 &

fslview sub-mon001_ses-M0_T2w.nii.gz -l Greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_lesionseg.nii.gz -l Red -t 0.7 &
```

</details>

During further debugging, I also discovered that`sct_deepseg_lesion` with `-v 2` flag fails on the following error:

<details><summary>output</summary>

```
$ sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -v 2 -r 0                                        

--
Spinal Cord Toolbox (git-master-c57b43f715cb85dad87a33623c7caf0ed47543ca)

sct_deepseg_lesion -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -v 2 -r 0
--


Method:
	Centerline algorithm: svm
	Assumes brain section included in the image: False

Loaded sub-mon001_ses-M0_T2w.nii.gz (/Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz) orientation LPI shape (63, 320, 320)
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134940.636032-5z75sp7p)
Reorient the image to RPI, if necessary...
Affine matrix: 
[[-7.99823999e-01 -8.07573553e-03  1.48307504e-02  2.15871563e+01]
 [-5.79589698e-03  7.91190743e-01  1.18252650e-01 -1.22633926e+02]
 [ 1.58612058e-02 -1.18118845e-01  7.91072965e-01 -2.36985718e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Saving image to image_in_RPI_res.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134940.636032-5z75sp7p/image_in_RPI_res.nii) orientation RPI shape (101, 512, 320)

Finding the spinal cord centerline...
Loaded image_in_RPI_res.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134940.636032-5z75sp7p/image_in_RPI_res.nii) orientation RPI shape (101, 512, 320)
Detecting the spinal cord using OptiC
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134947.234467-hwulxu2_)
Saving image to img_rpi_uint16.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134947.234467-hwulxu2_/img_rpi_uint16.nii) orientation RPI shape (101, 512, 320)
Loaded img_rpi_uint16_optic_ctr.hdr (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134947.234467-hwulxu2_/img_rpi_uint16_optic_ctr.hdr) orientation RPI shape (101, 512, 320)
Remove temporary files...
rm -rf /var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134947.234467-hwulxu2_

Cropping the image around the spinal cord...
Normalizing the intensity...
Saving image to image_in_RPI_res_norm.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134940.636032-5z75sp7p/image_in_RPI_res_norm.nii) orientation RPI shape (48, 48, 320)
load data...
Affine matrix: 
[[-4.98900115e-01 -5.04733482e-03  1.48307504e-02  2.15871563e+01]
 [-3.61526245e-03  4.94494200e-01  1.18252650e-01 -1.22633926e+02]
 [ 9.89362318e-03 -7.38242790e-02  7.91072965e-01 -2.36985718e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Segmenting the MS lesions using deep learning on 3D patches...
Loaded image_in_RPI_res_norm_resampled3d.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134940.636032-5z75sp7p/image_in_RPI_res_norm_resampled3d.nii) orientation RPI shape (48, 48, 512)
Saving image to image_in_RPI_res_norm_resampled3d_lesionseg.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134940.636032-5z75sp7p/image_in_RPI_res_norm_resampled3d_lesionseg.nii) orientation RPI shape (48, 48, 512)
load data...
Affine matrix: 
[[-4.98900115e-01 -5.04733482e-03  9.26921889e-03  2.15871563e+01]
 [-3.61526245e-03  4.94494200e-01  7.39079043e-02 -1.22633926e+02]
 [ 9.89362318e-03 -7.38242790e-02  4.94420588e-01 -2.36985718e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Loaded image_in_RPI_res_norm_resampled3d_lesionseg_resampled2d.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122134940.636032-5z75sp7p/image_in_RPI_res_norm_resampled3d_lesionseg_resampled2d.nii) orientation RPI shape (48, 48, 320)

Reassembling the image...
Saving image to /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_res_RPI_seg.nii.gz orientation RPI shape (101, 512, 320)
Resampling the segmentation to the original image resolution...
load data...
Affine matrix: 
[[-4.98900115e-01 -5.04733482e-03  1.48307504e-02  2.15871563e+01]
 [-3.61526245e-03  4.94494200e-01  1.18252650e-01 -1.22633926e+02]
 [ 9.89362318e-03 -7.38242790e-02  7.91072965e-01 -2.36985718e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Loaded /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_RPI_seg.nii.gz orientation RPI shape (63, 320, 320)
load data...
Traceback (most recent call last):
  File "/usr/local/lib/sct/python/envs/venv_sct/lib/python3.8/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'image_in_RPI_res_ctr.nii'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_deepseg_lesion.py", line 173, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/sct_latest/spinalcordtoolbox/scripts/sct_deepseg_lesion.py", line 148, in main
    im_seg, im_labels_viewer, im_ctr = deep_segmentation_MSlesion(im_image, contrast_type, ctr_algo=ctr_algo, ctr_file=manual_centerline_fname,
  File "/usr/local/lib/sct_latest/spinalcordtoolbox/deepseg_/lesion.py", line 235, in deep_segmentation_MSlesion
    resampling.resample_file(fname_res_ctr, fname_res_ctr, initial_resolution,
  File "/usr/local/lib/sct_latest/spinalcordtoolbox/resampling.py", line 157, in resample_file
    nii = nib.load(fname_data)
  File "/usr/local/lib/sct/python/envs/venv_sct/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: 'image_in_RPI_res_ctr.nii'                            
```

</details>

I also checked the behaviour of `-r 0` within `sct_deepseg_sc` and it is the same-- the centreline is also deleted.

<details><summary>output</summary>

```
$ sct_deepseg_sc -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -r 0                                                 

--
Spinal Cord Toolbox (git-master-c57b43f715cb85dad87a33623c7caf0ed47543ca)

sct_deepseg_sc -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -r 0
--

Config deepseg_sc:
  Centerline algorithm: svm
  Brain in image: False
  Kernel dimension: 2d
  Contrast: t2
  Threshold: 0.7
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135439.936724-kwivp76g)
Reorient the image to RPI, if necessary...
Finding the spinal cord centerline...
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135446.456076-a21mhdpb)
Remove temporary files...
rm -rf /var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135446.456076-a21mhdpb
Cropping the image around the spinal cord...
Normalizing the intensity...
Segmenting the spinal cord using deep learning on 2D patches...
Reassembling the image...
Resampling the segmentation to the native image resolution using linear interpolation...
Binarizing the resampled segmentation...
Compute shape analysis: 100%|##############| 238/238 [00:00<00:00, 399.93iter/s]
Found isolated voxels on slice 0, Removing them

Done! To view results, run one of the following commands (depending on your preferred viewer):
fsleyes /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz -cm greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz -cm red -a 70.0 &

fslview_deprecated /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz -l Greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz -l Red -t 0.7 &

fslview /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz -l Greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz -l Red -t 0.7 &                                              
```
</details>

Additionally, I tried to run `sct_deepseg_sc` with `-v 2` flag to see if it works or fails. And it is working.

<details><summary>output</summary>

```
$ sct_deepseg_sc -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -r 0 -v 2                                           

--
Spinal Cord Toolbox (git-master-c57b43f715cb85dad87a33623c7caf0ed47543ca)

sct_deepseg_sc -i sub-mon001_ses-M0_T2w.nii.gz -c t2 -brain 0 -r 0 -v 2
--

Loaded /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz orientation LPI shape (63, 320, 320)
Loaded /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz orientation LPI shape (63, 320, 320)
Config deepseg_sc:
  Centerline algorithm: svm
  Brain in image: False
  Kernel dimension: 2d
  Contrast: t2
  Threshold: 0.7
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135732.536049-n96qjol2)
Reorient the image to RPI, if necessary...
Affine matrix: 
[[-7.99823999e-01 -8.07573553e-03  1.48307504e-02  2.15871563e+01]
 [-5.79589698e-03  7.91190743e-01  1.18252650e-01 -1.22633926e+02]
 [ 1.58612058e-02 -1.18118845e-01  7.91072965e-01 -2.36985718e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Saving image to image_in_RPI_res.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135732.536049-n96qjol2/image_in_RPI_res.nii) orientation RPI shape (101, 512, 320)
Finding the spinal cord centerline...
Loaded image_in_RPI_res.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135732.536049-n96qjol2/image_in_RPI_res.nii) orientation RPI shape (101, 512, 320)
Detecting the spinal cord using OptiC
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135739.637178-z92j8v0z)
Saving image to img_rpi_uint16.nii (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135739.637178-z92j8v0z/img_rpi_uint16.nii) orientation RPI shape (101, 512, 320)
Loaded img_rpi_uint16_optic_ctr.hdr (/private/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135739.637178-z92j8v0z/img_rpi_uint16_optic_ctr.hdr) orientation RPI shape (101, 512, 320)
Remove temporary files...
rm -rf /var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221122135739.637178-z92j8v0z
Cropping the image around the spinal cord...
Normalizing the intensity...
Segmenting the spinal cord using deep learning on 2D patches...
Reassembling the image...
Resampling the segmentation to the native image resolution using linear interpolation...
Binarizing the resampled segmentation...
Affine matrix: 
[[-7.99823999e-01 -8.07573553e-03  1.48307504e-02  2.15871563e+01]
 [-5.79589698e-03  7.91190743e-01  1.18252650e-01 -1.22633926e+02]
 [ 1.58612058e-02 -1.18118845e-01  7.91072965e-01 -2.36985718e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Compute shape analysis: 100%|##############| 238/238 [00:00<00:00, 412.22iter/s]
Found isolated voxels on slice 0, Removing them
File /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz already exists. Will overwrite it.
Saving image to /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz orientation LPI shape (63, 320, 320)

Done! To view results, run one of the following commands (depending on your preferred viewer):
fsleyes /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz -cm greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz -cm red -a 70.0 &

fslview_deprecated /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz -l Greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz -l Red -t 0.7 &

fslview /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w.nii.gz -l Greyscale /Users/valosek/Desktop/centerline_isssue/canproco/sub-mon001/ses-M0/anat/sub-mon001_ses-M0_T2w_seg.nii.gz -l Red -t 0.7 &

```
</details>

### Conclusion

* both `sct_deepseg_lesion` and `sct_deepseg_sc` delete the centreline even with `-r 0` flag
* `sct_deepseg_lesion` finishes with an error when using `-v 2`
*  `sct_deepseg_sc` works fine with `-v 2`

**Comment by jcohenadad** [comment]
I _think_ this also concerns `sct_get_centerline`

**Comment by joshuacwnewton** [comment]
> Note: Although, `-r 0` is used to keep temporary files, the temporary folder with the centreline is deleted, see `rm -rf` line in the output.

Good catch! For some reason, the OptiC [`detect_centerline`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c57b43f715cb85dad87a33623c7caf0ed47543ca/spinalcordtoolbox/centerline/optic.py#L66-L131) function uses `verbose` instead of `remove_temp_files`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c57b43f715cb85dad87a33623c7caf0ed47543ca/spinalcordtoolbox/centerline/optic.py#L127-L129

This is why setting `verbose=2` properly preserves the files, as you noticed with `sct_deepseg_sc`.

> I _think_ this also concerns `sct_get_centerline`

Indeed! Setting `-r 0` for this script will have no effect, as well.

----

I can make sure that the value of `-r` propagates into this function, and also see if I can fixup that `-v 2` error with `sct_deepseg_lesion`.

**Comment by joshuacwnewton** [comment]
Just to make sure I wasn't missing any places where the centerline should be preserved via `-r`, I worked backwards from the `detect_centerline` function, and created a list of all of the functions that depend on it:

<details>

I've added a ✅ where a `remove_temp_files` argument is present (either existing, or added by me): 

- [X] `centerline/optic.py :: detect_centerline()`
    - [X] `sct_propseg.py :: propseg()`
    - [X] `centerline/core.py :: get_centerline()`
        - [ ] `csa_pmj.py :: get_slices_for_pmj_distance()` 
            - [ ] `sct_process_segmentation :: main()` 
        - [X] `deepseg_/sc.py :: find_centerline()`
            - [X] `deepseg_/sc.py :: deep_segmentation_spinalcord()`
                - [X] `sct_deepseg_sc.py :: main()` 
            - [X] `deepseg_/lesion.py :: deep_segmentation_MSlesion()`
                - [X] `sct_deepseg_lesion.py :: main()`
        - [ ] `flattening.py :: flatten_sagittal()`
            - [ ] `sct_flatten_sagittal.py :: main()`
            - [ ] `vertebrae/detect_c2c3.py :: detect_c2c3()` 
                - [X] `sct_label_vertebrae :: main()` 
        - [ ] `labels.py :: continuous_vertebral_levels()`
            - [ ] `sct_label_utils.py :: main()`
        - [ ] `process_seg.py :: compute_shape()`
            - [ ] `sct_process_segmentation :: main()`
            - [ ] `deepseg_/postprocessing.py :: _remove_isolated_voxels_on_the_edge()` 
        - [ ] `registration/labeling.py :: project_labels_on_spinalcord()` 
            - [X] `sct_register_to_template.py :: main()` 
        - [ ] `sct_analyze_lesion.py :: AnalyzeLeion().angle_correction()`
            - [ ] `sct_analyze_lesion.py :: AnalyzeLeion().analyze()`
                - [ ] `sct_analyze_lesion.py :: AnalyzeLeion()` 
                    - [X] `sct_analyze_lesion.py :: main()` 
        - [X] `sct_get_centerline.py :: main()`
        - [ ] `slice.py :: Sagittal.get_center_spit()`
            - [ ] `slice.py :: Slice.single()`
                - [ ] `qc.py :: generate_qc()` 
                    - [ ] `sct_qc.py :: main()`
        - [ ] `straightening.py :: _get_centerline()`
            - [ ] `straightening.py :: SpinalCordStraightener.straighten()`
                - [X] `straightening.py :: SpinalCordStraightener()` 
                    - [X] `sct_straighten_spinalcord.py :: main()`
                    - [X] `sct_register_to_template :: main()`  
            - [ ] `csa_pmj.py :: get_slices_for_pmj_distance()` 
                - [ ] `sct_process_segmentation :: main()` 
        - [ ] `vertebrae/core.py :: label_discs()`
            - [ ] `vertebrae/core.py :: label_vert()` 
               - [X] `sct_label_vertebrae :: main()` 
            - [ ] `vertebrae/core.py :: vertebral_detection()`
               - [X] `sct_label_vertebrae :: main()` 

</details>

For most of these entries, centerline detection is run using the default parameters, defined via [`ParamCenterline()`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c4f05f6d923dc7e2e78bc3e345cdaa111916bb34/spinalcordtoolbox/centerline/core.py#L13-L34) -- meaning that there are no user-facing options to tweak the centerline method. In those cases, I'm not sure how much value there is to preserving the centerline for debugging purposes.

That said, there are a few exceptions; the following additional scripts _do in fact_ expose the centerline method via two arguments: `-centerline-algo` and `-centerline-smooth`:

1. `sct_register_to_template`
2. `sct_straighten_spinalcord`
3. `sct_process_segmentation`

For these scripts, I think there's merit in keeping the centerline for debugging purposes. Plus, the first two scripts already have `-r` arguments, too, so that makes things quite easy! 

But, we'd have to add an `-r` argument for `sct_process_segmentation`, and it would only be useful for `-angle-corr 1`  :thinking:

**Comment by joshuacwnewton** [comment]
Ah! So, it turns out that intermediate files are _only_ generated for `optic`, and not for any of the other methods inside of `get_centerline` (`polyfit`/`bspline`/`linear`, etc.).

This means that even if a user specifies `-r 0` to keep the `optic` centerline files, they won't be able to easily debug the output from the non-optic centerline methods.

So, I'm thinking that managing temporary files should perhaps be handled by the outerl `get_centerline` function, rather than the `optic`-specific function. This will require a little more refactoring, but I think it will make debugging the centerline output much nicer. :)

**Comment by valosekj** [comment]
> For most of these entries, centerline detection is run using the default parameters, defined via [`ParamCenterline()`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c4f05f6d923dc7e2e78bc3e345cdaa111916bb34/spinalcordtoolbox/centerline/core.py#L13-L34) -- meaning that there are no user-facing options to tweak the centerline method. In those cases, I'm not sure how much value there is to preserving the centerline for debugging purposes.

For example, in the case I'm exploring, `sct_deepseg_lesion` with the default centreline method (i.e., `svm` aka `optic`):

```
sct_deepseg_lesion -i ${file}.nii.gz -c ${contrast}
```
provides different results than `sct_deepseg_lesion` with manually provided centreline obtained by `sct_propseg_sc` (`sct_propseg_sc` provides two outputs - SC segmentation and centreline detected by the `optic`):

```
sct_deepseg_lesion -i ${file}.nii.gz -c ${contrast} -file_centerline ${centerline_obtained_by_propseg}
```

Thus, I would like to compare the centreline obtained by `sct_deepseg_lesion` with the centreline obtained by `sct_propseg_sc`. In other words, I am not tweaking centreline parameters; I just need to preserve the file itself.

**Comment by joshuacwnewton** [comment]
Sorry for the confusion, I miscommunicated.

In [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3956#issuecomment-1325426050), there is a list (hidden under "Details) containing 11 uses of the `get_centerline` function. (Not just `sct_deepseg_lesion` and `sct_deepseg_sc`.)

I was saying that most of those extra uses do not need to add a `remove_temp_files` option.

**Comment by joshuacwnewton** [comment]
Ah, my apologies! #3960 was primarily focused on the centerline files.

So, I think addressing the `-v 2` issues may have slipped through the cracks. :sweat:

**Comment by valosekj** [comment]
No problem! Thank you for opening the new issue!

**Comment by kiristern** [comment]
@joshuacwnewton I am unable to see the temporary files with `sct_deepseg_sc -r 0`. I tried with and without `-v 2` but they are always being removed:
```
Remove temporary files...
rm -rf /var/folders/hd/7kkcl2qd5xq_6x2gc7_dcj100000gn/T/sct-20230116121620.337179-_px8uu7f
```

**Comment by jcohenadad** [comment]
@kiristern can you show us the output of `sct_version`

**Comment by joshuacwnewton** [comment]
Just to expand on @jcohenadad's request: 

This issue was fixed by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3960, which was included in SCT v5.8 and released in late November 2022.

So, to get this fix, you will need to either install [SCT v5.8](https://github.com/spinalcordtoolbox/spinalcordtoolbox/releases/tag/5.8), or [install from source](https://spinalcordtoolbox.com/user_section/installation/linux.html#option-2-install-from-github-development). 

(`sct_version` will let us double-check what your current version of SCT is, to compare to these requirements.)

**Comment by kiristern** [comment]
yep, was about to comment, but then hopped in a meeting. Issue was indeed a version problem. 

To recap, in case others come across the same issue:

After pulling and checking out to the latest version with:

```
git checkout master
git pull
git checkout 5.8
```

and confirming that `git status` showed `HEAD detached at 5.8`. I tried reinstalling with `pip install -e .` but was still getting the error. @valosekj helped debug, whereby calling `which sct_deepseg_sc` showed it was still pointing to version 5.7. 

This can modified by changing the path in `~/.zshrc` (or `~/.bashrc`); or calling `./install_sct` instead will add the new path automatically. 

Problem is indeed fixed in v5.8, thanks!
