### ISSUE TITLE
`totalspineseg` emits "nnUNet_{raw,preprocessed,results} is not defined" warning

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4711]
It looks like this slipped through my review. :sweat: 

```
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.

nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.

nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.
```

Not 100% urgent, since it doesn't affect processing, but it still doesn't look great for users to see this warning during installation of SCT. 

I'm not sure if this gets fixed when the models are installed? If so, maybe we can just manually silence this warning...

**Comment by valosekj** [comment]
I use this hack to temporarily suppress these nnUNet warnings:

https://github.com/ivadomed/model-spinal-rootlets/tree/main/packaging_ventral_rootlets#step-3-getting-the-predictions

Didn't we already implement something like this into `sct_deepseg`?

**Comment by joshuacwnewton** [comment]
Ahhhh... thank you for the reminder! We do include this hack:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/75ef29d3960f0aa6c3fddce5f40f819d4d72753b/spinalcordtoolbox/deepseg/nnunet.py#L5-L10

However, because it's only included in `deepseg/nnunet.py` these values don't get set when we call `sct_check_dependencies` and import `totalspineseg`.

**Comment by NathanMolinier** [comment]
Do I need to change something in the package ? Or we need to add these lines just on the SCT side ?

**Comment by NathanMolinier** [comment]
I edited the code to add these exports outside of the functions, see:
https://github.com/neuropoly/totalspineseg/blob/c2a5f21301eb08f5db0e52b2039d574470a26438/totalspineseg/init_inference.py#L7-L12

https://github.com/neuropoly/totalspineseg/blob/c2a5f21301eb08f5db0e52b2039d574470a26438/totalspineseg/inference.py#L11-L16

So it should be fixed in the version [20241127](https://pypi.org/project/totalspineseg/) of the package. Could you test with the new version of the package @joshuacwnewton ?

**Comment by joshuacwnewton** [comment]
Thanks for the update! If I upgrade totalspineseg (using the command `pip install totalspineseg -U` inside the venv), I get `totalspineseg-20241127`. However I still see the following when running `sct_check_dependencies`:

![image](https://github.com/user-attachments/assets/0ad1819e-3d0d-41e4-b66b-fdafb62c0c7d)

**Comment by NathanMolinier** [comment]
Could you check again now ? I made sure to update the variable before importing any nnunet functions

**Comment by joshuacwnewton** [comment]
LGTM! 

![image](https://github.com/user-attachments/assets/d7c36f90-042e-4882-b6d4-1dac50b65764)
